import { db } from "@/db";
import { products, type NewProduct } from "@/db/schema";
import { sql } from "drizzle-orm";

const SAMPLE: NewProduct[] = [
  {
    sku: "ETI-001",
    name: "بسكويت توبز بالكريمة",
    category: "بسكويت",
    description: "بسكويت محشي كريمة الفانيلا — عبوة ملونة مناسبة للأطفال.",
    packetsPerCarton: 24,
    piecesPerPacket: 12,
    cartonPrice: 216,
    packetPrice: 9,
    piecePrice: 0.75,
    retailPiecePrice: 1,
    stockCartons: 14,
    imageUrl: "/products/biscuits.jpg",
    sortOrder: 1,
  },
  {
    sku: "ETI-002",
    name: "بسكويت ساندوتش كاكاو",
    category: "بسكويت",
    description: "ساندوتش بسكويت بحشوة الكاكاو الغنية — حجم عائلي.",
    packetsPerCarton: 20,
    piecesPerPacket: 8,
    cartonPrice: 200,
    packetPrice: 10,
    piecePrice: 1.25,
    retailPiecePrice: 1.75,
    stockCartons: 6,
    imageUrl: "/products/biscuits.jpg",
    sortOrder: 2,
  },
  {
    sku: "ETI-003",
    name: "شوكولاتة ميلك بار",
    category: "شوكولاتة",
    description: "ألواح شوكولاتة بالحليب — تُحفظ في مكان جاف وبارد.",
    packetsPerCarton: 30,
    piecesPerPacket: 12,
    cartonPrice: 360,
    packetPrice: 12,
    piecePrice: 1,
    retailPiecePrice: 1.5,
    stockCartons: 9,
    imageUrl: "/products/chocolate.jpg",
    sortOrder: 3,
  },
  {
    sku: "ETI-004",
    name: "شوكولاتة بندق فاخرة",
    category: "شوكولاتة",
    description: "شوكولاتة بحشوة البندق — الكمية غير متوفرة حالياً.",
    packetsPerCarton: 24,
    piecesPerPacket: 10,
    cartonPrice: 288,
    packetPrice: 12,
    piecePrice: 1.2,
    retailPiecePrice: 1.75,
    stockCartons: 0,
    imageUrl: "/products/chocolate.jpg",
    sortOrder: 4,
  },
  {
    sku: "ETI-005",
    name: "عصير برتقال 1 لتر",
    category: "عصائر",
    description: "عصير برتقال طبيعي 100% — صلاحية 12 شهراً.",
    packetsPerCarton: 12,
    piecesPerPacket: 6,
    cartonPrice: 300,
    packetPrice: 25,
    piecePrice: 4.17,
    retailPiecePrice: 6,
    stockCartons: 11,
    imageUrl: "/products/juice.jpg",
    sortOrder: 5,
  },
  {
    sku: "ETI-006",
    name: "عصير مانجو 250 مل",
    category: "عصائر",
    description: "عصير مانجو بعبوة صغيرة مناسبة للمدارس والرحلات.",
    packetsPerCarton: 24,
    piecesPerPacket: 8,
    cartonPrice: 240,
    packetPrice: 10,
    piecePrice: 1.25,
    retailPiecePrice: 2,
    stockCartons: 18,
    imageUrl: "/products/juice.jpg",
    sortOrder: 6,
  },
  {
    sku: "ETI-007",
    name: "شيبسي حار كبير",
    category: "شيبسي",
    description: "بطاطس مقرمشة بنكهة حارة — عبوة كبيرة.",
    packetsPerCarton: 30,
    piecesPerPacket: 20,
    cartonPrice: 420,
    packetPrice: 14,
    piecePrice: 0.7,
    retailPiecePrice: 1,
    stockCartons: 7,
    imageUrl: "/products/chips.jpg",
    sortOrder: 7,
  },
  {
    sku: "ETI-008",
    name: "شيبسي بالجبن",
    category: "شيبسي",
    description: "بطاطس مقرمشة بنكهة الجبن — مفضلة للأطفال.",
    packetsPerCarton: 30,
    piecesPerPacket: 20,
    cartonPrice: 420,
    packetPrice: 14,
    piecePrice: 0.7,
    retailPiecePrice: 1,
    stockCartons: 3,
    imageUrl: "/products/chips.jpg",
    sortOrder: 8,
  },
  {
    sku: "ETI-009",
    name: "مكرونة سباجيتي",
    category: "مكرونة",
    description: "مكرونة سباجيتي من القمح الصلب — درجة أولى.",
    packetsPerCarton: 20,
    piecesPerPacket: 10,
    cartonPrice: 200,
    packetPrice: 10,
    piecePrice: 1,
    retailPiecePrice: 1.5,
    stockCartons: 22,
    imageUrl: "/products/pasta.jpg",
    sortOrder: 9,
  },
  {
    sku: "ETI-010",
    name: "مكرونة قلم",
    category: "مكرونة",
    description: "مكرونة قلم قصير مناسب للسلطات والفرن.",
    packetsPerCarton: 20,
    piecesPerPacket: 10,
    cartonPrice: 190,
    packetPrice: 9.5,
    piecePrice: 0.95,
    retailPiecePrice: 1.5,
    stockCartons: 16,
    imageUrl: "/products/pasta.jpg",
    sortOrder: 10,
  },
  {
    sku: "ETI-011",
    name: "سائل غسيل أطباق 1 لتر",
    category: "منظفات",
    description: "سائل غسيل أطباق مركّز برائحة الليمون.",
    packetsPerCarton: 12,
    piecesPerPacket: 6,
    cartonPrice: 240,
    packetPrice: 20,
    piecePrice: 3.33,
    retailPiecePrice: 5,
    stockCartons: 10,
    imageUrl: "/products/detergent.jpg",
    sortOrder: 11,
  },
  {
    sku: "ETI-012",
    name: "مسحوق غسيل 3 كجم",
    category: "منظفات",
    description: "مسحوق غسيل آلي عالي الرغوة المنخفض — عبوة 3 كجم.",
    packetsPerCarton: 8,
    piecesPerPacket: 4,
    cartonPrice: 320,
    packetPrice: 40,
    piecePrice: 10,
    retailPiecePrice: 14,
    stockCartons: 5,
    imageUrl: "/products/detergent.jpg",
    sortOrder: 12,
  },
];

let seedPromise: Promise<void> | null = null;

async function runSeed() {
  try {
    const [row] = await db.select({ count: sql<number>`count(*)::int` }).from(products);
    if ((row?.count ?? 0) > 0) return;
    await db.insert(products).values(SAMPLE);
  } catch {
    // الجداول غير مهيأة بعد — سيتم التجاهل بأمان
  }
}

/** يزرع بيانات نموذجية مرة واحدة إذا كان جدول الأصناف فارغاً */
export async function ensureSeed(): Promise<void> {
  if (!seedPromise) {
    seedPromise = runSeed().catch(() => undefined);
  }
  await seedPromise;
}
